name: GitHub Actions Demo
run-name: ${{ github.actor }} is running test on ${{github.ref}} ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Execute tests
        python -m unittest discover -s ./src
      - name: Coverage report
        run: coverage run -m unittest discover -s ./src
      - name: HTML report
        run: coverage report && coverage html
      - name: Upload Archive coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage folder
          path: htmlcov/**
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      

      
